- id: pydoclint
  name: pydoclint
  description: "A Python docstring linter that checks arguments, returns, yields, and raises sections"
  entry: pydoclint
  language: python
  types: [python]
  require_serial: true
